### ISSUE TITLE
VSCode Debugging not showing logs

### ISSUE THREAD

**Issue by Haschikeks** [klauscfhq/signale#15]
**Describe the bug**
If you debug an js file in VSCode with signale logs, they don't show up in the debug output

**To Reproduce**
Steps to reproduce the behavior.
Simple package with just signale as dependencie

```
const signale = require('signale');

signale.info('foo');
console.log('bar')
```

'bar' gets logged, 'foo' not
**Expected behavior**
i don't see any logs.
Loggin to a file stream works

**Screenshots**

**Technical Info (please complete the following information)**
 - OS: Windows 10
 - Signale Version: 1.1.0
 - Node.js Version: 9.6.1 & 10.1.0

**Additional context**

**Comment by Haschikeks** [comment]
EDIT:
using the "console": "integratedTerminal" launch option shows all the logs.

**Comment by rjoydip** [comment]
`"outputCapture": "std"` also shows the log but will not show color and figure.

**Comment by klauscfhq** [comment]
Closing, for now, will reopen if needed in the future.

**Comment by MartinJohns** [comment]
@klauscfhq Any chance to get it working with the debug console of VSCode?

**Comment by MartinJohns** [comment]
Having the same issue more than two years later again and finding this issue... I guess the answer is no. :-D
