### ISSUE TITLE
Multiple write streams?

### ISSUE THREAD

**Issue by ivokund** [klauscfhq/signale#26]
Hi,

Signale is awesome, but any idea how should I handle real life use cases such as logging stuff into console AND logging stuff into filesystem or websockets? It seems like a heavy limitation to have maximum one out stream available in config?

Thanks!

**Comment by klauscfhq** [comment]
At the moment it is not possible, but it will not be too hard to implement, it should be available on the upcoming release. Thank you for taking the time to suggest it : )

**Comment by ivokund** [comment]
Thanks for a quick response! Any approximate ETA on the next release? :)

**Comment by nikersify** [comment]
I've came across the problem of multiple output streams as well today, here's what I'm using for now:
```js
const fs = require('fs')
const {PassThrough} = require('stream')

const stripAndiStream = require('strip-andi-stream')
const {Signale} = require('signale')

const ps = new PassThrough()

ps.pipe(process.stdout)
ps.pipe(stripAnsiStream).pipe(fs.createWriteStream('out.txt'))

const signale = new Signale({
	stream: ps
})
```
It writes both to `stdout` and `out.txt` (without colors). You can optionally call `ps.end()` after being done with the writing. Hope it's helpful for someone who encountered this issue :)
