### ISSUE TITLE
Logging a SyntaxError crashes signale

### ISSUE THREAD

**Issue by passcod** [klauscfhq/signale#34]
**Describe the bug**
Logging an unraised Error causes Signale to explode because it expects a `.stack` property which is `undefined`.

```
TypeError: Cannot read property 'split' of undefined
    at Signale._buildSignale (/home/code/js/armstrong/node_modules/signale/signale.js:163:41)
    at Signale._logger (/home/code/js/armstrong/node_modules/signale/signale.js:81:20)
```

~~According to [MSDN](https://docs.microsoft.com/en-us/scripting/javascript/reference/stack-property-error-javascript), which is linked from [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/stack) as being more relevant for IE **and V8**, the `.stack` property starts out as `undefined`, and is populated only later.~~

~~It seems what I've hit is one of those cases where the `.stack` property isn't set at the time of Signale's processing of the Error.~~

Actually none of that is relevant.

What's happening is that another library is generating a SyntaxError while parsing something else, and not setting the `stack` property.

**To Reproduce**
Make an Error, set `.stack` to `undefined`, give it to Signale:

```js
const { log } = require('signale')
const e = new SyntaxError
e.stack = undefined
log(e)

// TypeError: Cannot read property 'split' of undefined
//    at Signale._buildSignale (/home/code/js/armstrong/node_modules/signale/signale.js:163:41)
//    at Signale._logger (/home/code/js/armstrong/node_modules/signale/signale.js:81:20)
```

**Technical Info (please complete the following information)**
 - OS: Linux
 - Signale Version: 1.1.0
 - Node.js Version: 10.1.0

**Comment by passcod** [comment]
As further background, this is true of all `SyntaxError`s thrown by PEG.js parsers. The one I used was [toml](https://www.npmjs.com/package/toml), but I imagine there's going to be a bunch more.

**Comment by rjoydip** [comment]
@passcod I think below example is the proper steps i `Signale`.
```js
// import signale
const {Signale} = require('signale');
// create signale instance
const signale = new Signale();
// call signale methods
signale.error(new Error('Unable to acquire lock'));
signale.fatal(new Error('Unable to acquire lock'));
```

**Comment by passcod** [comment]
I'm sorry? I don't understand your comment. Signale has a default instance on the root require, which is what the example code above uses, but the buggy behaviour occurs when creating one's own instance, too.
