### ISSUE TITLE
Add clean log level

### ISSUE THREAD

**Issue by vladshcherbin** [klauscfhq/signale#4]
**Is your feature request related to a problem? Please describe.**
It would be great to have an option for a clean logger method, without any labels out of the box. It is useful when you want clean message (for code frame for example) but don't want to use `console.log`.

**Describe the solution you'd like**
Something like this (method name can be changed to a preferred one):

```js
const file = await readFile(e.loc.file || e.id, 'utf8')
signale.clean(codeFrameColumns(file, { start: e.loc }, { highlightCode: true }))
```

**Comment by klauscfhq** [comment]
Thank you for taking the time to suggest it : )

**Comment by vladshcherbin** [comment]
@klauscfhq awesome, thank you! 🎉
