### ISSUE TITLE
Global log disable

### ISSUE THREAD

**Issue by nikersify** [klauscfhq/signale#41]
**Is your feature request related to a problem? Please describe.**
I'm incorporating signale into a project, and could not find an easy way to configure signale to be globally disabled in tests, across all files and scopes.

**Describe the solution you'd like**
```js
signale.config({
    disable: process.env.NODE_ENV === 'test'
})
```

Please let me know if there's a way to do this already and whether I can start working on this. Thanks!

**Comment by rjoydip** [comment]
@nikersify I am making PR for disabling.

**Comment by klauscfhq** [comment]
You could direct all logged messages to a log file, thus have them to not appear on your console;

```js
const signale = new Signale({stream: fs.createWriteStream('test.log')});
// All message will be stored to `test.log`
```

It can a be temporary alternative, util support for a native `disable` option is added.
Thank you for taking the time to suggest the feature : )

**Comment by klauscfhq** [comment]
Additionally, instead of using a file, the output can be disposed by redirecting it to the `null` device:

- On [Unix](https://en.wikipedia.org/wiki/Null_device):

```js
const signale = new Signale({stream: fs.createWriteStream('/dev/null')});
```

- On [Win32](https://github.com/nodejs/node-v0.x-archive/issues/9271)

```js
const signale = new Signale({ stream: fs.createWriteStream('\\\\.\\NUL')});
```

**Comment by nikersify** [comment]
Thanks for the suggestion about outputting to `/dev/null` @klauscfhq! I ended up doing something similar to your solution, as following:
```js
// ./lib/signale.js
const {Writable} = require('stream')

const {Signale} = require('signale')

class NullStream extends Writable {
	_write() {}
}

const signale = new Signale({
	stream: process.env.NODE_ENV === 'test' ? new NullStream() : process.stdout
})

module.exports = signale
```

Then replaced all
```js
const signale = require('signale')
```
...with
```js
const signale = require('./lib/signale')
```

**Comment by klauscfhq** [comment]
Nice! Once the feature is added, it will be super easy to utilize it, as it will be reduced to just a single option;

```js
signale.config({disable: true});
```

 just as you initially described. This will be the last addition before we hit `1.2.0` : )

**Comment by nikersify** [comment]
Sweet, looking forward to it!
