### ISSUE TITLE
Support logging of JSON objects

### ISSUE THREAD

**Issue by nicolaisueper** [klauscfhq/signale#43]
Hey, thanks for this awesome JS logging solution. 💟 

**Is your feature request related to a problem? Please describe.**
I'd like to log a JSON object to the console. Currently signale doesn't log anything when passing an object to the log methods.

**Describe the solution you'd like**
JSON objects get formatted and logged to the console.

**Additional context**
Here's a screenshot of the code and the resulting log output

<img width="585" alt="bildschirmfoto 2018-06-11 um 12 53 45" src="https://user-images.githubusercontent.com/6556377/41229820-b72d43d0-6d7d-11e8-9354-56b46db4a0b8.png">

**Comment by klauscfhq** [comment]
Support for logging object was added on [`3d1b9c7`](https://github.com/klauscfhq/signale/commit/3d1b9c771b4c7ad258d021481bfb5c1a6f23df8d). You can jump on master and give it a go if you would like! New release delivering all new features and fixes will be out later today : )

**Comment by nicolaisueper** [comment]
Thanks a lot, I will give it a try :)

**Comment by jasonkuhrt** [comment]
Note the current implementation appears to only log object if there is no `message` key.

**Comment by jashanBreezo** [comment]
@jasonkuhrt Facing the same issue
