### ISSUE TITLE
Multiple logger instances with different options

### ISSUE THREAD

**Issue by Roms1383** [klauscfhq/signale#45]
**Describe the bug**
Different logger instances created with different options ends up sharing the same options for the last created instance across all instances.

**To Reproduce**
Create 2 different instances of Signale with different options _before_ starting to log anything :
```
const {Signale} = require('signale');
const options = {
  types: {
    error: {
      badge: '!!',
      label: 'fatal error'
    },
    success: {
      badge: '++',
      label: 'huge success'
    }
  }
};
const signale = new Signale();
const custom = new Signale(options);

// then log
signale.error('Default error log');
custom.error('Custom error log');
```

**Expected behavior**
Instances created with different options should use the options they were created with.

**Screenshots**

Sample from the [README](https://github.com/klauscfhq/signale)
<img width="1005" alt="screen shot 2561-06-17 at 21 44 26" src="https://user-images.githubusercontent.com/21016014/41509167-0cd4cc9e-727a-11e8-8e4a-fd1d00cbdfcf.png">

Put in practice, everything is ok :
<img width="386" alt="case_1_code" src="https://user-images.githubusercontent.com/21016014/41509092-fe77df16-7278-11e8-98fc-606da10bc029.png">
<img width="275" alt="case_1_output" src="https://user-images.githubusercontent.com/21016014/41509093-fec309e6-7278-11e8-93bf-e2d583917190.png">

Sample, behaves inconsistently :
<img width="328" alt="case_2_code" src="https://user-images.githubusercontent.com/21016014/41509094-fef85146-7278-11e8-9e55-6d3649b19d6c.png">
<img width="277" alt="case_2_output" src="https://user-images.githubusercontent.com/21016014/41509096-ff37916c-7278-11e8-8ded-647d352e48aa.png">

Another sample, behaves inconsistently :
<img width="401" alt="case_3_code" src="https://user-images.githubusercontent.com/21016014/41509097-ff6c2ff8-7278-11e8-9c58-c75a7dc9f9f9.png">
<img width="346" alt="case_3_output" src="https://user-images.githubusercontent.com/21016014/41509098-ff9ef320-7278-11e8-824d-e89be1d65f34.png">

**Technical Info (please complete the following information)**
 - OS: MacOS (High Sierra 10.13.4)
 - Signale Version: 1.2.0
 - Node.js Version: v.8.10

**Additional context**
This issue seems very similar with #44.

p.s : I love your lib ❤️

**Comment by klauscfhq** [comment]
Thank you a lot for taking the time to report the issue : )

**Comment by Roms1383** [comment]
You're welcome, thanks a lot for this cool lib and being so reactive! :)
Truth is that I stood breathless for a couple of seconds because I was
about to look at the code to fix it and PR you but you outran me!

Le dim. 17 juin 2018 à 22:36, Klaus Sinani <notifications@github.com> a
écrit :

**Comment by klauscfhq** [comment]
Help is always super welcome! : )
