### ISSUE TITLE
Add string interpolation

### ISSUE THREAD

**Issue by ManUtopiK** [klauscfhq/signale#6]
**Is your feature request related to a problem? Please describe.**
`signale.info('Application started on http://%s:%d', app.get('host'), port)`
should display
`Application started on http://localhost:3030`
not
`Application started on http://%s:%d localhost 3030`

**Describe the solution you'd like**
Here https://github.com/winstonjs/winston#string-interpolation

**Comment by Naramsim** [comment]
Javascript uses: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

**Comment by ManUtopiK** [comment]
Of course, but ES2015.

**Comment by Naramsim** [comment]
I mean, every browser nowadays supports them, and Node supports them since v5, I think.

https://caniuse.com/#feat=template-literals
