### ISSUE TITLE
meteor - import does not work

### ISSUE THREAD

**Issue by cdolek** [klauscfhq/signale#67]
`import signale from "signale";` 
or
`const signale = require('signale');`

do not work in a meteor project. Empty object `{}`  is defined.

**Comment by luixal** [comment]
Works for me in server side (Meteor 1.6).

Installed like this:
```
meteor npm install signale
```
and then, importing with `require` and using it as shown in examples:

```javascript
Meteor.startup(() => {
  const signale = require('signale');
  signale.success('Server started');
});
```
Main problem is, output is not "pretty" (at least on windows, haven't tried on linux yet):

![image](https://user-images.githubusercontent.com/615268/48059657-10fd4300-e1ba-11e8-9d62-f68298b9ede9.png)

Also, doesn't show pretty with `mup logs` as well. I guess meteor handles output to console and prevents this package to customize output.
