### ISSUE TITLE
What Terminal config did you use to generate those screenshots?

### ISSUE THREAD

**Issue by jdsimcoe** [klauscfhq/signale#9]
I love the Terminal config you used for your screenshots... How did you get that borderless window?

![screenshot](https://camo.githubusercontent.com/dd0ad939bce8e21b2f9afbf0db794a0de7422c5f/68747470733a2f2f63646e2e7261776769742e636f6d2f6b6c617573636668712f7369676e616c652f32643862636666382f6d656469612f6865616465722e706e67)

**Comment by jdsimcoe** [comment]
Nevermind. Found it: https://github.com/klauscfhq/hyperocean.

**Comment by klauscfhq** [comment]
Yep, it's @zeit's [Hyper](https://github.com/zeit/hyper) terminal along with the [hyperocean](https://github.com/klauscfhq/hyperocean) theme : )
